name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
    
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            vult-linux.tar.gz
            vult-osx.tar.gz
            vult-win.zip
            vultweb.js
            vultlib.js
            vultc.js
            vultc.h
